kartverket/kvib

- docusaurus.config.js
- package.json
> KVIB Searchbar

- apps/storybook/stories/design-tokens/ikoner.mdx
Har oppdatert dokumentasjonssiden for KVIB ikonene med hvordan de skal tas i bruk.
> KVIB-156 Dokumentere design tokens: Ikoner

- .changeset/swift-eyes-sing.md
- README.md
- apps/storybook/.storybook/preview.js
- apps/storybook/stories/documentation/komigang.mdx
- apps/storybook/stories/documentation/oppsett.mdx
- packages/react/README.md
I denne PRen har jeg oppdatert teksten i `readmen` som ligger på rot i repoet, og i `packages/react`, samt på oppsettsiden i storybook.
> KVIB-157 Oppdatere readme og "oppsett" i dokumentasjonen

- .changeset/olive-actors-cough.md
- apps/storybook/stories/design-tokens/Breakpoints.tsx
- apps/storybook/stories/design-tokens/Radii.tsx
- apps/storybook/stories/design-tokens/design-tokens.mdx
- packages/react/src/theme/foundations/breakpoints.ts
- packages/react/src/theme/foundations/index.ts
Lagt til design tokens for breakpoints.
Gjort en liten endring på hvordan radius eksemplene vises i Storybook.
> KOMP-40 Breakpoints

- .changeset/large-donuts-smile.md
- .changeset/spicy-points-hope.md
- apps/storybook/stories/design-tokens/Colors.tsx
- apps/storybook/stories/design-tokens/design-tokens.mdx
- packages/react/src/theme/foundations/colors.ts
* Lagt til fargen black
* Dokumentert fargetokens i Storybook
> KOMP-41 Fargetokens

- .changeset/strange-candles-fry.md
- apps/storybook/stories/design-tokens/Borders.tsx
- apps/storybook/stories/design-tokens/design-tokens.mdx
- packages/react/src/theme/foundations/borders.ts
- packages/react/src/theme/foundations/index.ts
* Lagt til borders/outlines tokens + dokmentert i Storybook
* Dokumentert spacings, sizes, z-indekses
> KOMP-82 Borders/outlines + dokumentere andre gjenværende tokens

- .changeset/wild-oranges-divide.md
- apps/storybook/stories/components/Button/Button.stories.tsx
- apps/storybook/stories/components/TextLink/TextLink.mdx
- apps/storybook/stories/components/TextLink/TextLink.stories.tsx
- packages/react/src/index.ts
- packages/react/src/link/TextLink.tsx
- packages/react/src/link/index.tsx
- packages/react/src/theme/components/index.ts
- packages/react/src/theme/components/link.ts
- packages/react/src/theme/foundations/shadows.ts
* Laget TextLink-komponenten
* Endret shadows outline tokenet.
> KOMP-60: TextLink

- .changeset/old-dodos-kick.md
- .changeset/olive-colts-talk.md
- packages/react/src/badge/index.ts
- packages/react/src/card/index.ts
- packages/react/src/code/index.ts
- packages/react/src/divider/index.ts
- packages/react/src/kbd/index.ts
- packages/react/src/list/index.ts
- packages/react/src/stat/index.ts
- packages/react/src/table/index.ts
- packages/react/src/tag/index.ts
Eksportert alle Data display-komponenter
- Badge
- Card
- Divider
- Kbd
- List
- Stat
- Table
- Tag
> KOMP-104: Data display-komponenter

- .changeset/young-feet-rhyme.md
- packages/react/src/hooks/index.tsx
- packages/react/src/index.ts
Eksportert chakra utility hooks:  
-useBoolean,  
-UseBreakpointValue,  
-useClipboard,  
-useConst,  
-useControllable,  
-useDimensions,  
-useDisclosure,  
-useMergeRefs,  
-useMediaQuery,  
-useOutsideClick,  
-usePrefersReducedMotionuseTheme,  
-useToken
> Komp 113- utility hooks

- .changeset/old-nails-grow.md
- packages/react/src/button/index.tsx
- packages/react/src/radio/index.tsx
Har revertert de kvibifiserte komponentene:
* Button
* Radio (+ Radiogroup)
Heading, Text og Link ble revertert i tidligere PR
> KOMP-114: Reverere kvibifiserte komponenter

- .changeset/honest-pots-give.md
- packages/react/src/theme/index.ts
Fjerne custom styling fra kvibifiserte komponenter
> NO-JIRA Fjerne custom styling fra kvibifiserte komponenter

- .changeset/lazy-kings-drum.md
- packages/react/src/theme/tokens/shadows.ts
- packages/react/src/theme/tokens/z-index.ts
Legge til riktig verdi for shadow outline
> NO-JIRA: Legge til riktig verdi for shadow outline

- apps/storybook/.storybook/main.js
- apps/storybook/package.json
- package-lock.json
Legger til a11y til storybook. 
- Synstest vil vises som et accessibility-ikon til høyre på hver story.
- En ny fane for accessibility vil vises nederst ved siden av "Controls". Her kjøres det tester hver gang en komponent oppdateres. 
Se oppdatert beskrivelse i [bidragsløypa](https://kartverket.atlassian.net/wiki/spaces/TB/pages/616464426/Guidelines+for+bidragsl+ypa).
> Komp 151 a11y

- .github/workflows/storybook-tests.yml
- apps/storybook/.storybook/test-runner.ts
- apps/storybook/package.json
- apps/storybook/stories/components/tabs/Tabs.stories.tsx
- package-lock.json
- packages/react/src/tabs/index.ts
- Lagt til  Storybooks Test Runner som en workflow (test runner) i github actions.
- Lagt til en test-runner.ts fil for å konfigurere a11y gjennom test-runner
> KOMP-185, test runner

- apps/storybook/stories/documentation/bidra.mdx
-bugfix: rettet opp i bugs i  "bidra.mdx"
- la til major.minor.patch documentation i bidra.mdx.
> KOMP-168, bugfix: corrected docs

- apps/storybook/stories/components/slider/Slider.mdx
- apps/storybook/stories/components/slider/Slider.stories.tsx
lagt til dokumentasjon for slider komponent i storybook.
> Komp 152, sliderDocs

- apps/storybook/stories/components/Input/Input.mdx
La til import dokumentasjon for Input- Group, Addon og Element.
> Addded documentation for InputGroup, Addon and Element.

- .changeset/eleven-plants-learn.md
- apps/storybook/stories/components/data-display/code/Code.mdx
- apps/storybook/stories/components/data-display/code/Code.stories.tsx
Legger til dokumentasjon til Code.
> Komp-179-code

- .changeset/weak-tomatoes-behave.md
- apps/storybook/stories/components/data-display/divider/Divider.mdx
- apps/storybook/stories/components/data-display/divider/Divider.stories.tsx
Legger til dokumentasjon for divider. 
> Komp-180-divider

- .changeset/honest-pigs-laugh.md
- apps/storybook/stories/components/data-display/kbd/Kbd.mdx
- apps/storybook/stories/components/data-display/kbd/Kbd.stories.tsx
Legger til dokumentasjon for Kbd.
> Komp-183-kbd

- apps/storybook/stories/components/data-display/tag/Tag.mdx
- apps/storybook/stories/components/data-display/tag/Tag.stories.tsx
Legger til dokumentasjon for Tag.
> KOMP-188-tag

- apps/storybook/stories/components/Typography/Heading/Heading.mdx
- apps/storybook/stories/components/Typography/Heading/Heading.stories.tsx
Legger til dokumentasjon for Heading.
> KOMP-190-heading

- apps/storybook/stories/components/Typography/highlight/Highlight.mdx
- apps/storybook/stories/components/Typography/highlight/Highlight.stories.tsx
Legger til dokumentasjon for highlight.
> KOMP-191-highlight

- apps/storybook/stories/components/Typography/Text/Text.mdx
- apps/storybook/stories/components/Typography/Text/Text.stories.tsx
Legger til dokumentasjon for Text.
> KOMP-192-text

- apps/storybook/stories/components/avatar/Avatar.mdx
- apps/storybook/stories/components/avatar/Avatar.stories.tsx
Legger til dokumentasjon for avatar.
> KOMP-193-avatar

- apps/storybook/stories/components/breadcrumb/Breadcrumb.mdx
- apps/storybook/stories/components/breadcrumb/Breadcrumb.stories.tsx
Legger til dokumentasjon til Breadcrumb.
> KOMP-194-breadcrumb

- apps/storybook/stories/documentation/bidra/KjenteProblemer.mdx
Legger til en docs-side for kjente problemer. 
Den er delt opp i: 
**Storybook** 
Problem 1 
- Problem
- Løsning
Problem 2
- Problem
- Løsning
**Chakra**
Problem 1 
- Problem
- Løsning
Problem 2
- Problem
- Løsning
osv.
> KOMP-197-kjenteProblemer

- apps/storybook/index.html
- apps/storybook/stories/components/circular-progress/CircularProgress.mdx
- apps/storybook/stories/components/circular-progress/CircularProgress.stories.tsx
Legger til dokumentasjon for Circular Progress.
> KOMP-196-circularProgress

- apps/storybook/stories/components/close-button/CloseButton.mdx
- apps/storybook/stories/components/close-button/CloseButton.stories.tsx
Legger til dokumentasjon for Close Button.
> KOMP-201-closeButton

- .changeset/wet-socks-begin.md
- apps/storybook/stories/components/file-upload/FileUpload.mdx
- apps/storybook/stories/components/file-upload/FileUpload.stories.tsx
- apps/storybook/stories/components/search/Search.mdx
- apps/storybook/stories/components/search/Search.stories.tsx
- packages/react/src/file-upload/FileUpload.tsx
- packages/react/src/file-upload/index.ts
- packages/react/src/search/Search.tsx
- packages/react/src/search/index.ts
> Komp 199 search

- .changeset/funny-eagles-occur.md
la til Filopplasting komponent.
> La til FileUpload dokumentasjon.

- apps/storybook/stories/components/editable/Editable.mdx
- apps/storybook/stories/components/editable/Editable.stories.tsx
Legger til dokumentasjon for editable.
> KOMP-203-editable

- apps/storybook/stories/components/image/Image.mdx
- apps/storybook/stories/components/image/Image.stories.tsx
Legger til dokumentasjon for Image.
> KOMP-204-image

- apps/storybook/stories/components/tabs/Tabs.stories.tsx
- apps/storybook/stories/documentation/bidra/Teste.mdx
Oppdatert a11y regel for å unngå Aria value violation i Tabs komponent.
> Added a11y rule to tabs to change aria violation

- apps/storybook/stories/components/menu/Menu.mdx
- apps/storybook/stories/components/menu/Menu.stories.tsx
- apps/storybook/stories/components/menu/srcStrings.ts
- package-lock.json
Legger til dokumentasjon for Menu.
> Komp-208-menu

- apps/storybook/stories/components/modal/Modal.mdx
- apps/storybook/stories/components/modal/Modal.stories.tsx
- apps/storybook/stories/components/modal/srcStrings.ts
Legger til dokumentasjon for Modal.
> KOMP-211-modal

- packages/react/src/index.ts
Det virker som at man har glemt en linje for å tilgjengeliggjøre search
> Export search

- .changeset/calm-bugs-fix.md
- packages/react/src/index.ts
Oppdatert index fil for eksport av komponenter.
> Oppdatert komponent export fil.

- apps/storybook/stories/components/search/Search.mdx
Legger til warning om feil på søkefelt.
> KOMP-212-searchBug

- apps/storybook/.storybook/theme.js
Endret Logo URL tilbake til /storybook.
> Oppdatert theme.js. Logo URL.

- apps/storybook/stories/components/range-slider/RangeSlider.mdx
- apps/storybook/stories/components/range-slider/RangeSlider.stories.tsx
Legger til dokumentasjon for Range Slider.
> KOMP-219-rangeSlider

- apps/storybook/stories/components/select/Select.mdx
- apps/storybook/stories/components/select/Select.stories.tsx
Legger til dokumentasjon for Select.
> KOMP-221-select

- apps/storybook/stories/components/show-hide/ShowHide.mdx
- apps/storybook/stories/components/show-hide/ShowHide.stories.tsx
Legger til dokumentasjon for Show/Hide.
> KOMP-223-showHide

- apps/storybook/stories/components/skeleton/Skeleton.mdx
- apps/storybook/stories/components/skeleton/Skeleton.stories.tsx
Legger til dokumentasjon for Skeleton.
> KOMP-224-skeleton

- apps/storybook/stories/components/spinner/Spinner.mdx
- apps/storybook/stories/components/spinner/Spinner.stories.tsx
Legger til dokumentasjon for Spinner.
> KOMP-236-spinner

- apps/storybook/stories/components/stepper/Stepper.mdx
- apps/storybook/stories/components/stepper/Stepper.stories.tsx
- apps/storybook/stories/components/stepper/srcStrings.ts
Legger til dokumentasjon for Stepper.
> KOMP-238-stepper

- .changeset/mean-bats-sneeze.md
- packages/react/src/theme/components/button.ts
Fjerner hvit bakgrunn på outlined button. Den skal være transparent.
> KOMP-235-buttonOutline

- apps/storybook/stories/components/switch/Switch.mdx
- apps/storybook/stories/components/switch/Switch.stories.tsx
Legger til dokumentasjon for Switch.
> KOMP-241-switch

- apps/storybook/stories/documentation/bidra/Style.mdx
- apps/storybook/stories/documentation/taIBruk.mdx
- package-lock.json
* Lagt til dokumentasjon i oppsett-fila om hvordan man endrer default fargetema for hele applikasjonen.
* Lagt til dokumentasjon i style-fila om hvordan man endrer default fargetema for et enkelt komponent.
* Lagt til dokumentasjon i oppsett-fila om hvordan man unngår å bruke komponenter direkte fra Chakra ved et uhell.
> Oppdatert dokumentasjon i hht KOMP-171 og KOMP-229

- .changeset/orange-toys-impress.md
Legger til changeset for å oppdatere pakka. Footer er exponert.
> Eksponert footer changeset

- .changeset/nervous-pets-press.md
- apps/storybook/stories/components/button/Button.stories.tsx
- apps/storybook/stories/components/icon-button/IconButton.stories.tsx
- packages/react/src/button/Button.tsx
- packages/react/src/button/IconButton.tsx
- packages/react/src/theme/components/button.ts
- packages/react/src/theme/components/iconButton.ts
Endrer navn på verdier i proppen "variant" på knapper. 
Det tok meg 5-10 minutter. Relativt lett å få til dersom komponentene allerede er "kvibifisert".
> KOMP-246-propsnavn

- .changeset/sharp-lobsters-smell.md
- apps/storybook/stories/components/search/search-async/SearchAsync.stories.tsx
- packages/react/src/search-async/SearchAsync.tsx
- Endrer type på handleFromChange slik at searchAsync er lettere å bruke. 
- Legger til id på searchAsync.
- Endrer navn på handleFromChange til onChange. Bedre navngiving.
> Forenkler SearchAsync

- apps/storybook/.storybook/theme.js
- apps/storybook/stories/components/tooltip/Tooltip.mdx
- apps/storybook/stories/components/tooltip/Tooltip.stories.tsx
Legger til dokumentasjon for tooltip.
> KOMP-247-tooltip

- .changeset/cool-kangaroos-shave.md
- apps/storybook/stories/design/Icon.mdx
- packages/react/src/icon/index.ts
Eksporterer MaterialSymbols så man slipper å importere fra MUI.
> KOMP-253-muiType

- apps/storybook/stories/documentation/introduksjon.mdx
Prøvde å oppdatere branchen til Wanni, men ble tull med branch-navn, så den endte opp med å pushe til en ny branch i stedet (tror det skyldes ø i branch-navnet).
Jeg har fikset lenken til å vises som lenke, og i tillegg lagt til KVIB-styling på intro-siden.
Lenkene er fremedles ikke riktig stylet, fordi det er problemer med å vise ikoner i storybook.
> Spørreundersøkelse

- .changeset/nine-falcons-double.md
- apps/storybook/stories/components/search/search-async/SearchAsync.mdx
- apps/storybook/stories/components/search/search-async/SearchAsync.stories.tsx
- packages/react/src/search-async/SearchAsync.tsx
- packages/react/src/search-async/index.tsx
- Legger til støtte for multiselect 
- Forenkler typer i props
> KOMP-248-asyncSelectMulti

- .github/workflows/release.yml
- .github/workflows/slack-notify.yml
- .github/workflows/testSlack.yml
Legger til github actions workflow for å publisere en notifikasjon om ny versjon i channel på slack: #kvib-status.
> KOMP-278-slack

- .changeset/plenty-pots-perform.md
- apps/storybook/.storybook/MDXContainer.jsx
- apps/storybook/.storybook/docs-root.css
- apps/storybook/.storybook/manager.js
- apps/storybook/.storybook/preview.js
- apps/storybook/.storybook/theme.js
- apps/storybook/stories/components/Input/Input.mdx
- apps/storybook/stories/components/data-display/card/Card.mdx
- apps/storybook/stories/components/data-display/kbd/Kbd.mdx
- apps/storybook/stories/components/data-display/table/Table.mdx
- apps/storybook/stories/components/drawer/Drawer.mdx
- apps/storybook/stories/components/menu/Menu.mdx
- apps/storybook/stories/components/modal/Modal.mdx
- apps/storybook/stories/components/popover/Popover.mdx
- apps/storybook/stories/components/portal/Portal.mdx
- apps/storybook/stories/components/search/search/Search.mdx
- apps/storybook/stories/components/slider/Slider.mdx
- apps/storybook/stories/components/stepper/Stepper.mdx
- apps/storybook/stories/components/textarea/Textarea.mdx
- apps/storybook/stories/components/tooltip/Tooltip.mdx
- apps/storybook/stories/documentation/bidra/Bygge.mdx
- apps/storybook/stories/documentation/bidra/Dokumentere.mdx
- apps/storybook/stories/documentation/bidra/KjenteProblemer.mdx
- apps/storybook/stories/documentation/bidra/Publish.mdx
- apps/storybook/stories/documentation/bidra/Style.mdx
- apps/storybook/stories/documentation/bidra/Teste.mdx
- apps/storybook/stories/documentation/introduksjon.mdx
- package-lock.json
Endrer stil på storybook + legger KvibProvider i MDX og fjerner der den ikke trengs lenger.
> [WIP] KOMP-277-stil

- apps/storybook/stories/design/ColorPalettes.tsx
Legger til opacity 100% på kartfarger.
> KOMP-299-kartfarger100

- packages/react/src/theme/components/slider.ts
Vi har nå stroke på slider thumb
> fikset theme fila og satte stroke farge på sliderThumb

- apps/storybook/stories/design/design-tokens/Colors.tsx
Endrer til flex i tokens for at fargene skal wrappe + fikser litt småting
> KOMP-297-colorsFix

- apps/storybook/stories/components/alert-dialog/AlertDialog.mdx
- apps/storybook/stories/components/alert-dialog/AlertDialog.stories.tsx
- apps/storybook/stories/components/alert-dialog/srcStrings.ts
Legger til dokumentasjon for AlertDialog.
> KOMP-303-alertDialog

- .changeset/weak-cycles-reflect.md
- apps/storybook/stories/design/Icon.mdx
- packages/react/src/icon/index.ts
- packages/react/src/index.ts
Legger til ny import for symbols og warning om hva man må gjøre hvis det ikke funker.
> komp-307-symbols

- apps/storybook/stories/documentation/taIBruk.mdx
Legger til oppsett for hvordan man bruker designsystemet i remix.
> komp-312-remix

- .github/workflows/slack-notify.yml
Endrer slackmelding til å passe nytt navn.
> KOMP-317-slackmessage

- .github/workflows/pharos-scan.yml
> Code scan med Pharos  (lagde ny branch uten changes fra gammel branch)

- .changeset/kind-singers-teach.md
- apps/storybook/stories/components/search/search/Search.mdx
- apps/storybook/stories/components/search/search/Search.stories.tsx
- packages/react/src/search/Search.tsx
Nullstilt Search komponent pga. feil med knapp.
> KOMP-328-Search-Reset

- apps/storybook/.storybook/docs-root.css
- package-lock.json
- package.json
> Forandret farger på slider thumb på både mozilla og chrome/edge

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/new-component.yml
- .github/ISSUE_TEMPLATE/update-component.yml
Må legge til disse før jeg kan lage tilbakemeldingsknapp.
> Legger til issue templates

- .github/dependabot.yml
Endrer dependabot til å kjøre weekly - daily blir for ofte, mye bråk i prs.
> komp-343-dependabot

- apps/storybook/stories/components/data-display/code/Code.mdx
- apps/storybook/stories/components/data-display/code/Code.stories.tsx
- apps/storybook/stories/templates/Template.mdx
- Legger til ny docs for code i henhold til mal.
- Legger til en template for malen som gjør det enklere å oppdatere komponentene!
> Komp-334-code

- apps/storybook/.storybook/docs-root.css
- apps/storybook/.storybook/theme.js
Endrer på stilen til sidemenyen i henhold til design🎨
Et ønske fra Erlend om å gjøre sidemenyen litt mer custom. Endringer er gjort så godt det kan gjøres - storybook har sine begrensninger✌️
Ønske:
> Sidemenucustom

- apps/storybook/stories/documentation/bidra/KjenteProblemer.mdx
Legger til kjent problem: ikoner i docs.
> komp-311-kjentproblem

- .changeset/shaggy-penguins-punch.md
- apps/storybook/stories/components/button/Button.mdx
- apps/storybook/stories/components/button/Button.stories.tsx
- packages/react/src/theme/components/button.ts
Docs for button i henhold til ny mal😎
> Komp-350-button

- .changeset/spicy-falcons-unite.md
- apps/storybook/stories/components/search/search/Search.mdx
- apps/storybook/stories/components/search/search/Search.stories.tsx
- packages/react/src/button/IconButton.tsx
- packages/react/src/search/Search.tsx
Ønske i #gen-designsystem:
- Endrer typen på size på IconButton slik at det er lettere å bruke den i sammensatte komponenter
- Legger til props for å endre på søkeknappen på search (buttonWidth, buttonVariant)
> Komp-361-search

- apps/storybook/stories/components/Layout/Box/Box.mdx
- apps/storybook/stories/components/Layout/Box/Box.stories.tsx
Endrer docs i henhold til mal for box.
> komp-352-box

- apps/storybook/stories/components/search/search/Search.mdx
- apps/storybook/stories/components/search/search/Search.stories.tsx
Endrer docs i henhold til mal for search.
> komp-356-search

- apps/storybook/stories/documentation/IntroCard.tsx
- apps/storybook/stories/documentation/introduksjon.mdx
Forsiden var outdated på teksten så jeg tok en gjennomgang. 
- Oppdaterer tekst og gjør det mer oversiktlig 
- Legger til kort for enda mer oversikt
> komp-363-intro

- .changeset/three-mice-cry.md
- .changeset/tough-dodos-collect.md
- apps/storybook/CHANGELOG.md
- apps/storybook/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
Reverts kartverket/kvib#651
Skulle ikke vært merget pga pakkefix pull-request.
> Revert "Version Packages"

- apps/storybook/stories/components/select/Select.mdx
- apps/storybook/stories/components/select/Select.stories.tsx
Endrer dokumentasjon for select i henhold til mal.
> komp-357-select

- .github/workflows/codeql.yml
> komp-382 Create codeql.yml

- .changeset/proud-spoons-deny.md
- packages/react/src/search/Search.tsx
Fjernet type search, la til role="search".
> Komp 378 search type bugfix

- .changeset/swift-seas-tease.md
- apps/storybook/stories/components/checkbox/Checkbox.stories.tsx
- packages/react/src/theme/components/checkbox.ts
Changed invalid checkbox backgroundColor to red.
> KOMP-387-Invalid-Checkbox

- apps/storybook/stories/components/progress/Progress.mdx
- apps/storybook/stories/components/progress/Progress.stories.tsx
Oppdaterte dokumentasjonen for progress
> Komp 375 progress

- apps/storybook/.storybook/manager-head.html
Fjernet koden fra headeren som lar hotjar tracke oss. 
Dette betyr at vi ikke lenger får hotjar sin innsikt inntil videre.
> Fjernet tracking code for hotjar fra headeren

- apps/storybook/stories/components/skjemaelementer/number-input/NumberInput.mdx
- apps/storybook/stories/components/skjemaelementer/number-input/NumberInput.stories.tsx
Oppdatert props dokumentasjon for NumberInput.
> NumberInput Documentation update

- .github/workflows/slack-notify.yml
Changed Slack Notify message to include changelog.
> Changed Slack Notify message to include changelog.

- .changeset/rich-dolphins-warn.md
- packages/react/src/theme/components/checkbox.ts
- packages/react/src/theme/components/radio.ts
Opprettet invalid theme for Radio knapp.
> KOMP-436-Radio-Checkbox-State

- .changeset/two-frogs-know.md
- packages/react/src/file-upload/FileUpload.tsx
- packages/react/src/theme/components/fileUpload.ts
- packages/react/src/theme/components/index.ts
Opprettet theme fil for FileUpload komponent.
> Added theme file for FileUpload comp

- .changeset/fast-pans-fry.md
- .github/workflows/slack-notify.yml
- package-lock.json
- package.json
Oppdatert Slack Workflow og Turbo version.
> Changed slack workflow, updated Turbo version.

- .changeset/green-spiders-fetch.md
- apps/storybook/stories/components/sideelementer/header/Header.stories.tsx
- apps/storybook/stories/components/sideelementer/logo/Logo.stories.tsx
- packages/react/assets/logo_horizontal.tsx
- packages/react/assets/logo_vertical.tsx
- packages/react/src/header/Header.tsx
- packages/react/src/logo/Logo.tsx
Lagt til role og aria-label på Logo komponent.
> added role and aria-label to Logo svg.

- apps/storybook/stories/components/skjemaelementer/number-input/NumberInput.mdx
- apps/storybook/stories/components/skjemaelementer/number-input/NumberInput.stories.tsx
Oppdatert NumberInput dokumenter.
> KOMP-441-NumberInput-docs

- apps/storybook/stories/components/skjemaelementer/Input/Input.mdx
- apps/storybook/stories/components/skjemaelementer/checkbox/Checkbox.mdx
- apps/storybook/stories/components/skjemaelementer/file-upload/FileUpload.mdx
- apps/storybook/stories/components/skjemaelementer/pin-input/PinInput.mdx
- apps/storybook/stories/components/skjemaelementer/pin-input/PinInput.stories.tsx
Oppdatert PinInput dokumentasjon.
> Pin input docs

- apps/storybook/stories/components/skjemaelementer/switch/Switch.mdx
- apps/storybook/stories/components/skjemaelementer/switch/Switch.stories.tsx
- package-lock.json
Oppdatert dokumentasjon for Switch komponent.
> KOMP-442-Switch

- apps/storybook/stories/components/skjemaelementer/textarea/Textarea.mdx
- apps/storybook/stories/components/skjemaelementer/textarea/Textarea.stories.tsx
- apps/storybook/stories/components/skjemaelementer/textarea/srcTextAreaStrings.ts
Oppdatert Textarea dokumentasjon.
> KOMP-443-Textarea

- .github/workflows/release.yml
- .github/workflows/slack-notify.yml
- apps/storybook/.storybook/manager.js
- apps/storybook/.storybook/preview.js
- apps/storybook/stories/components/media/avatar/Avatar.mdx
- apps/storybook/stories/components/media/icon/Icon.mdx
- apps/storybook/stories/components/media/image/Image.mdx
- apps/storybook/stories/documentation/changelog.mdx
- apps/storybook/stories/introduksjon.mdx
Oppdatert dokumentasjonssider under Media kategori.
Endret Sidebar oppsett for lettere navigering.
> Komp-446-media

- apps/storybook/stories/components/Typography/Heading/Heading.mdx
- apps/storybook/stories/components/Typography/Text/Text.mdx
- apps/storybook/stories/components/Typography/highlight/Highlight.mdx
Oppdatert komponent dokumentasjoner under Typografi.
> komp-453-typografi

- apps/storybook/stories/components/sideelementer/divider/Divider.mdx
- apps/storybook/stories/components/sideelementer/footer/footer-inline/FooterInline.mdx
- apps/storybook/stories/components/sideelementer/footer/footer/Footer.mdx
- apps/storybook/stories/components/sideelementer/header/Header.mdx
- apps/storybook/stories/components/sideelementer/logo/Logo.mdx
Oppdatert sideelementer komponent dokumentasjoner.
> komp-449-sideelementer

- apps/storybook/stories/components/datavisning/accordion/Accordion.mdx
- apps/storybook/stories/components/datavisning/badge/Badge.mdx
- apps/storybook/stories/components/datavisning/kbd/Kbd.mdx
- apps/storybook/stories/components/datavisning/list/List.mdx
- apps/storybook/stories/components/datavisning/list/List.stories.tsx
- apps/storybook/stories/components/datavisning/stat/Stat.mdx
- apps/storybook/stories/components/datavisning/table/Table.mdx
- apps/storybook/stories/components/datavisning/tag/Tag.mdx
- apps/storybook/stories/templates/DocsHeading.tsx
Oppdatert Datavisning komponent dokumentasjoner.
> Komp-447-Datavisning

- apps/storybook/stories/components/Layout/AspectRatio/ApectRatio.mdx
- apps/storybook/stories/components/Layout/Box/Box.mdx
- apps/storybook/stories/components/Layout/Center/Center.mdx
- apps/storybook/stories/components/Layout/Container/Container.mdx
- apps/storybook/stories/components/Layout/Flex/Flex.mdx
- apps/storybook/stories/components/Layout/Flex/Flex.stories.tsx
- apps/storybook/stories/components/Layout/Grid/Grid.mdx
- apps/storybook/stories/components/Layout/SimpleGrid/SimpleGrid.mdx
- apps/storybook/stories/components/Layout/Stack/Stack.mdx
- apps/storybook/stories/components/Layout/Wrap/Wrap.mdx
- apps/storybook/stories/components/Layout/Wrap/Wrap.stories.tsx
Oppdatert Layout komponent dokumentasjoner.
> Komp-448-Layout

- .changeset/spotty-tomatoes-vanish.md
- apps/storybook/stories/components/knapper/button/Button.stories.tsx
- apps/storybook/stories/components/tilbakemelding/alert/Alert.stories.tsx
- packages/react/src/theme/components/alert.ts
- packages/react/src/theme/components/button.ts
- packages/react/src/theme/components/index.ts
Fargejustering for Toast og Alert Error-tilstand.
- Endret Toast and Alert-komponentens Error state farger til å bruke colors.red[100], colors.red[500] og colors.red[600], ned fra colors.red[800].
- Endret standard colorScheme til grønt for Button komponent i theme filen.
> Komp 455 alert

- .changeset/violet-chicken-listen.md
- packages/react/src/theme/components/index.ts
- packages/react/src/theme/components/modal.ts
Som diskutert mellom designere på Slack.
> Modal overlay fra blackAlpha 600 til blackAlpha 700

- apps/storybook/stories/documentation/utils/ComponentList.tsx
Referanse til Knapper og Typografi i Komponentoversikt siden virket ikke. 
Endret til riktig code ref.
> Komponentoversikt - Knapper og Typografi

- apps/storybook/stories/components/tilbakemelding/alert/Alert.mdx
- apps/storybook/stories/components/tilbakemelding/alert/Alert.stories.tsx
Oversatte dokumentasjonen for Alert til norsk, slik at den matcher resten av nettsiden.
> Språk i Alert

- .changeset/light-roses-attend.md
- package-lock.json
- packages/react/package.json
Oppdaterer react stately, som hadde legacy-swc-helpers som dependency (critical).
> [Security update] Oppdaterer react stately

- apps/storybook/stories/documentation/designere/startDesign.mdx
La til lenker i teksten der det var ønsket av designer. Skulle vært gjort forrige PR, men ble glemt.
> La til lenker jeg glemte å legge til i forrige pr

- apps/storybook/stories/documentation/designere/startDesign.mdx
Oppdrag fra designer Line Moen
> Endret alle lenkene til <Link/>

- package-lock.json
- package.json
> oppdaterte axios til nyeste version for å bli kvitt kritisk sårbarhet.

- packages/react/src/search-async/SearchAsync.tsx
> Fixed wonky imports

- .github/pull_request_template.md
- .github/workflows/slack-notify.yml
- apps/storybook/stories/components/Layout/Grid/Grid.mdx
- apps/storybook/stories/components/navigasjon/link/Link.stories.tsx
- apps/storybook/stories/components/sideelementer/header/Header.stories.tsx
- apps/storybook/stories/components/skjemaelementer/slider/Slider.mdx
- apps/storybook/stories/documentation/utils/IntroCard.tsx
- apps/storybook/stories/documentation/utviklere/bidra/Bygge.mdx
- apps/storybook/stories/documentation/utviklere/bidra/Dokumentere.mdx
- apps/storybook/stories/documentation/utviklere/bidra/Hurtigveiledning.mdx
- apps/storybook/stories/documentation/utviklere/bidra/KjenteProblemer.mdx
- apps/storybook/stories/documentation/utviklere/taIBruk.mdx
- apps/storybook/stories/introduksjon.mdx
- apps/storybook/stories/templates/Feedback.tsx
> Fikset alle lenkene jeg fant som pekte til ingenting. (Etter forrige omstrukturering)

- apps/storybook/stories/components/skjemaelementer/slider/Slider.mdx
Endret tre like avsnitt til ett
> Endret på Slider dokumentasjon

- apps/storybook/stories/components/datavisning/table/Table.stories.tsx
- packages/react/src/theme/components/table.ts
Liten forenkling av oppsettet for table, fjerner tomme defaults.
> Fjerner standardvariant som ble satt for table

- .changeset/strange-horses-carry.md
- package-lock.json
- packages/react/package.json
- packages/react/src/datepicker/Datepicker.tsx
Måtte refaktorere en god del av logikk og styling som et resultat av dette, men forhåpentligvis skal ting oppføre seg som før.
> Oppgraderer avhengighetene til Daypicker

- .changeset/empty-starfishes-double.md
- package-lock.json
- packages/react/package.json
- packages/react/src/hooks/index.tsx
I håp om å løse en byggfeil som er rapportert inn bumper jeg noen pakker og fjerner bruk av deprecated funksjoner som `useDimensions`.
> Oppdaterer Chakra til versjon 2.10.2

- .changeset/new-pets-notice.md
- apps/storybook/.storybook/docs-root.css
- apps/storybook/stories/components/overlay/modal/Modal.stories.tsx
- apps/storybook/stories/components/skjemaelementer/slider/Slider.stories.tsx
- apps/storybook/stories/components/tilbakemelding/alert/Alert.mdx
- packages/react/src/theme/components/closeButton.ts
- packages/react/src/theme/components/index.ts
I tillegg til å endre standardfargen til `CloseButton` fra grå til grønn på hover.
> Mindre endringer i dokumentasjonen

- apps/storybook/.storybook/preview.tsx
- apps/storybook/stories/design/tokens/Tokens.mdx
- apps/storybook/stories/design/tokens/Tokens.tsx
- apps/storybook/stories/documentation/designere/bidra.tsx
- apps/storybook/stories/documentation/utils/Feedback.tsx
Landingsside i Tokens-mappen med overordnet info om hva tokens er.
> Dokumentasjonsside for tokens

- .changeset/heavy-bananas-beam.md
- apps/storybook/stories/components/skjemaelementer/datepicker/Datepicker.stories.tsx
- apps/storybook/stories/components/skjemaelementer/daterangepicker/DateRangePicker.mdx
- apps/storybook/stories/components/skjemaelementer/daterangepicker/DateRangePicker.stories.tsx
- apps/storybook/stories/components/skjemaelementer/daterangepicker/DateRangePicker.tsx
- apps/storybook/stories/documentation/utils/Dokumentasjonsside.tsx
- apps/storybook/stories/documentation/utils/Listeelement.tsx
- apps/storybook/stories/documentation/utils/Tekstblokk.tsx
- packages/react/src/datepicker/DateRangePicker.tsx
- packages/react/src/datepicker/index.ts
Etter innspill fra teamene som bruker designsystemet var det flere som ønsket en måte å velge flere datoer på.
> Ny komponent: DateRangePicker

- .changeset/unlucky-schools-refuse.md
- apps/storybook/stories/components/button/Button.mdx
- apps/storybook/stories/components/button/Button.stories.tsx
- apps/storybook/stories/components/button/ButtonDocs.tsx
- apps/storybook/stories/components/list/List.stories.tsx
- apps/storybook/stories/components/radio-card/RadioCard.stories.tsx
- apps/storybook/stories/components/spinner/Spinner.stories.tsx
- apps/storybook/stories/documentation/utils/Dokumentasjonsside.tsx
- packages/react/src/components/ui/button.tsx
- packages/react/src/theme/components/button.ts
- packages/react/src/theme/components/spinner.ts
Pluss forbedring av dokumentasjon for Button
> Fiks for feil Spinner-farge på Button med loading-state

- .changeset/grumpy-turkeys-return.md
- packages/react/package.json
<!-- Sjekk av disse punktene for hver endring. Disse utgjør et minimum av sjekker som skal være gjennomført før PR-en merges. For mer informasjon om hvordan du kan bidra med kode til designbiblioteket, se https://design.kartverket.no/?path=/docs/for-utviklere-bidra-med-kode-hurtigveiledning--docs>
> Fix react peer dependencies

- .changeset/shy-memes-brake.md
- package-lock.json
- packages/react/package.json
Oppdaterer React peer dependency korrekt
> Update React peer dependency correctly (18 and up)
