.changeset/three-eggs-admire.md
package-lock.json
turbo.json

React-pakken ble publisert til npm, men den inkluderer ikke dist-filene. Prøver å finne ut hva feilen kan være, tror npm publish-greiene fungerer greit, men man må ha bygget filene for at den skal ha noe å publiere. Tror derfor feilen ligger i turbo, forhåpentligvis er det ikke for mye styr å fikse.

KVIB-116: Fiks react-bygg

---

package-lock.json

Forrige PR tok package.json og package-lock ut av sync etter at jeg renamet apps/storybook, denne fiksen gjør at man kan bruke npm ci igjen.

Fikser manglende sync mellom package og package-lock

---

.changeset/curvy-teachers-draw.md
apps/storybook/stories/components/tabs/Tabs.mdx
apps/storybook/stories/components/tabs/Tabs.stories.tsx
packages/react/src/tabs/index.ts
packages/react/src/theme/components/tabs.ts

Legger til props-imports til tabs. `<Tab>` og `TabList` fungerte som det skulle, men mulig brukerne vil ha tilgang til props typene. Fikser også riktig import på storyen i samme slengen.

Komp 147 tabs update

---

.changeset/thick-stingrays-develop.md
packages/react/src/index.ts
packages/react/src/theme-utils/index.ts

Vi bruker et par funksjoner fra [@chakra-ui/theme-utils](https://github.com/chakra-ui/chakra-ui/tree/main/packages/utilities/theme-utils) for å sette blå som standardtema i Nibas:
```
import { extendTheme, withDefaultColorScheme } from "@chakra-ui/react";
const customTheme = extendTheme(
withDefaultColorScheme({ colorScheme: "blue" }),
theme
);
```
Vi vil helst unngå å importere fra chakra for å unngå potensiell krøll, så det hadde vært kjekt å heller bare ha de funksjonene videresendt fra kvib
Alternative løsninger:
- Sette blå som standardtema i kvib dersom det er flere som bruker blå enn grønn (hvilke konsumenter av kvib bruker grønn per nå? Det krever noe innsikt for å avgjøre)
- La KvibProvider ta imot default-temanavn som en parameter i stedet, så slipper konsumentene å skrive …

Videresend et par theme-utils

---

.changeset/weak-boxes-behave.md
packages/react/src/toast/index.ts

Jeg tror jeg gjorde noe rart med branchen, men nå skal useToastOptions være videreeksportert på opprag fra NIBAS

Legg til toast type

---

.changeset/young-bikes-heal.md
packages/react/src/input/index.ts

La til InputGroup, Addons og Elements export fra Chakra. 
Midlertidig fix.

Enabled InputGroup, Addon, Elements.

---

.changeset/pink-ligers-draw.md
packages/react/src/button/Button.tsx

Fjerner prop på Button som skapte warning. Chakrabutton har ikke propen, så er nok bare en mistake fra tidligere.

🐛 KOMP-181-button-warning

---

.changeset/rich-apes-sparkle.md
apps/storybook/stories/components/data-display/stat/Stat.mdx
apps/storybook/stories/components/data-display/stat/Stat.stories.tsx

Legger til dokumentasjon for stat.

Komp-186-stat

---

.changeset/new-spoons-suffer.md
packages/react/src/theme/components/button.ts

Button (variant=outline) hopper litt på focus -> Ikke fjerne border, men heller sette den til samme farge som bakgrunnen.

🐛 KOMP-184-buttonBug

---

.github/workflows/chromatic.yml
apps/storybook/stories/documentation/bidra/Teste.mdx

Endrer chromatic til å kjøre når man legger til label "chromatic" på en PR. Dette gjør det enklere å lage et build til chromatic. Nå har jeg skrudd av UI-tests i chromatic - vet ikke om vi trenger de egentlig. Dette gjør at det ikke blir like mange snapshots. Vi har fortsatt UI-review, så får vi se hvordan det fungerer😎

Komp-210-chromatic

---

.github/workflows/chromatic.yml

Build chromatic på push til master. Grunnen til dette er at chromatic trenger status på master for å se hva som har blitt endret når en PR får en build.

KOMP-215-chromatic

---

.changeset/sharp-phones-sparkle.md
packages/react/src/form-control/Form-error-message.tsx

Legger til gap i feilmelding på form control. Det var ingen plass mellom ikon og tekst før.

KOMP-214-formControlbug

---

apps/storybook/stories/components/checkbox/Checkbox.stories.tsx
apps/storybook/stories/components/icon-button/IconButton.mdx
apps/storybook/stories/components/range-slider/RangeSlider.stories.tsx
apps/storybook/stories/components/select/Select.mdx
apps/storybook/stories/components/select/Select.stories.tsx
apps/storybook/stories/components/tabs/Tabs.stories.tsx
apps/storybook/stories/documentation/bidra/Style.mdx
packages/react/src/button/Button.tsx
packages/react/src/link/Link.tsx
packages/react/src/radio/Radio.tsx
packages/react/src/tabs/Tabs.tsx
packages/react/src/theme/components/button.ts
packages/react/src/theme/components/iconButton.ts
packages/react/src/theme/components/index.ts
packages/react/src/theme/components/link.ts
packages/react/src/theme/components/tabs.ts
packages/react/src/theme/index.ts

Prøvde å oppgradere kvib-versjonen min i nibas forleden, men møtte på en rekke problemer der halve applikasjonen ble grønn, mens den andre havlparten ble blå (altså sånn vi vil ha det i nibas). Nå følger ikke jeg veldig aktivt med på kvib, men det virker som at standardfargen som brukes på komponenter er grønn. Det er noe man kan sette sentralt for alle komponenter, så kan man eventuelt sette komponenter som skal være grå til å være det. Da blir det lettere for konsumenter å sette fargetemaet til sin applikasjon til å være f.eks. blå, fordi komponentene bare arver fargetema fra theme. Konsumenter og komponenter har enda all anledning til å overstyre fargetema, men med denne endringen slipper man å spesifikt si at alt skal være grønt eller blått eller hva nå enn.
Jeg prøvde å oppdatere …

Samkjører standard fargetema på tvers av komponenter

---

.changeset/tidy-cheetahs-begin.md
packages/react/src/icon/Icon.tsx

For å kunne style komponenter fra kvib via andre rammeverk som styled-components så må komponentene kunne ta imot className, det manglet på Icon. Når vi utvider komponenter fra Chakra så går det greit fordi vi som regel bruker en modifikasjon av chakra sine props typer, som inkluderer className. 
En bedre versjon av denne endringen ville vært å gjøre at Icon egentlig bare tar imot hva nå enn en span normalt kan ta imot, slik at man ikke blir begrenset av komponenter hvis man f.eks. vil sette en aria sak, men hadde ikke tid til å fikse det akkurat nå, dette er en forbedring uansett.

Legger til manglende className på Icon

---

apps/storybook/.storybook/manager-head.html
apps/storybook/.storybook/preview.js
apps/storybook/.storybook/theme.js

Endret litt på designet på storybook for å ta i bruk Kartverket sine farger og fonter der det var mulig. Spesifikt vår blåfarge, og lys blå på toolbar og addons + lys grå på sidebaren. Bruker også Mulish i stedet for Open Sans.
Før:
Etter:

Litt pimping på designet på storybook

---

.changeset/hungry-apes-run.md
packages/react/src/theme/components/iconButton.ts

Ref https://github.com/kartverket/kvib/pull/410 så innser jeg at vi kanskje bør øke størrelsen på ikonene for IconButton også, ikonene ble veldig små i Nibas i hvertfall. 
Tok utgangspunkt i de samme størrelsene til Button, men ser at knappen ellers er skrevet litt annerledes. Testet ut om jeg på en god måte kunne bare bruke button sine styles og overskrive dem ved behov, men møtte på snodige bugs, så jeg droppet det.

Øker størrelse på ikoner for IconButton

---

apps/storybook/stories/components/progress/Progress.mdx
apps/storybook/stories/components/progress/Progress.stories.tsx

Legger til dokumentasjon for Progress.

KOMP-217-progress

---

.changeset/wise-crews-explode.md
packages/react/src/pin-input/Pin-Input.tsx

Alle konsumenter av kvib får følgende feilmelding:
Det kommer av at vi bruker forwardRef å PinInput uten å bruke ref. Vi kan heller ikke bruke ref, ettersom PinInput fra Chakra ikke tar imot ref. Da er det ikke noe vits at vår PinInput tar imot ref heller, så da kan man fjerne forwardRef fra vår komponent slik at ikke alle konsumenter får feilmelding i konsollen sin uten noen peiling på hvor det kommer fra

Fjern forwardRef for PinInput som ikke tar imot ref

---

.github/workflows/preview.yml
apps/storybook/.storybook/theme.js
apps/storybook/index.html
apps/storybook/package.json
package-lock.json

Legger til github actions for preview url på github pages.
(Av en eller annen grunn så vil urlen til KVIB alltid endre seg til /kvib/storybook - noe som det virker som lager krøll for previews. Må undersøkes nærmere.) - Tror jeg fant svaret på dette: 
- Index.html i storybook redirected til /kvib/storybook, i tillegg til at det fantes et postbuild step i package.json. Dette ser ut som rester som ble brukt rundt tiden man flyttet/brukte old-kvib. Jeg fjernet postbuild og redirect, noe som forhåpentligvis vil fikse alle url-problemene vi har hatt. 
**Sjekk ut den første preview-urlen under**😎

KOMP-242-previewUrl

---

.github/workflows/deploy.yml

Det ser ut som at den github action workflowen vi brukte for å prodsette ikke støtter flere deployments i gh-pages branchen. Den skriver altså over hele branchen når man pusher til prod (da forsvinner pr-previews). 
-> Derfor bytter vi workflow til JamesIves, som skal løse dette problemet. Den er også mer brukt enn den KVIB brukte.
Må testes gjennom en prodsetting.

Ny prod-deploy action

---

apps/storybook/stories/components/tabs/Tabs.mdx
apps/storybook/stories/components/tabs/Tabs.stories.tsx

Fjerner isSelected fra dokumentasjonen til tabs.
isSelected eksisterer i dokumentasjonen til chakra, men er ikke en prop i tab.

KOMP-249-removeIsSelected

---

apps/storybook/stories/components/footer/Footer.stories.tsx
packages/react/src/footer/Footer.tsx

Jeg tipper at NRL kan hoppe over til å bruke kvib sin footer, men jeg vet at det har vært ønskelig at NRL kan kontaktes direkte fra footer. (ref. nrl@kartverket.no i den nederste footeren på bildet)
Legger til et skjermbilde av kvib footer vs NRL footer.
Vi har også Postadresse pluss en "tilbake til NRL" knapp. Kan dobbelt sjekke, men jeg tror ikke dette er viktig.
EDIT: Postadresse ligger inne i "[Kontaktinfo og adresser launch](https://kartverket.no/om-kartverket/kontakt-oss)" lenken deres så det må jo være ok

NRL ønsker direkte kontakt fra footer

---

.github/workflows/preview.yml

Legger til workflow dispatch for pr-preview.
Dette gjøres fordi dependabot ikke kan lage pr-previews for bumps fordi dependabot er sett på som "untrusted" av github.

KOMP-261-dependabotPreview

---

.changeset/proud-snakes-lay.md

Dependabot oppdaterer ikke automatisk changelog når den gjør endringer. Dette må vi få inn en rutine på å gjøre selv når vi godkjenner PRs fra dependabot som gjør endringer i react-pakka. Det glemte jeg i denne omgang, så denne pull-requesten gjelder changelog for den ene oppdateringen som påvirket react-pakka av de jeg har godkjent i denne omgang.

Lagt til changelog

---

.changeset/chatty-phones-join.md
packages/react/src/icon/Icon.tsx

Ikoner har ikke fungert i noen prosjekter. Dette burde være det som manglet.
Legger til material-symbols import.

KOMP-295-icons

---

.github/dependabot.yml

Legger til grupper basert på semver version. Det vil si at dependabot vil gruppere package-bumps i en pr for patch og minor, og en for major (forhåpentligvis). Da blir det raskere å oppdatere og det blir lettere å følge med på hva som lager breaking changes. 
Jeg skal se om det er mulig å få dependabot til å lage changesets.

KOMP-304-dependabot

---

.github/workflows/release.yml

**Endring:**
Endrer fra å bruke generisk github token til app token for å trigge flere workflows. 
**Hvorfor:**
For å sende updates til slack, må en ny workflow bli kjørt på github event `released`.
For at det skal være mulig å trigge en ny workflow på github event `released`, så kan ikke den forrige workflowen bli kjørt gjennom en github-token. En vanlig github-token har bare mulighet til å trigge sin egen workflow. Derfor må man enten bruke sin egen token, eller en app-token. Jeg valgte app-token slik at det er lett å bytte den ut/ gi andre eierskap - i tillegg til at det er lett å gi den riktige permissions. 
**Liten warning:** Usikker på om appen har fått nok permissions for å release - det må vi se på release.

KOMP-298: Ny token i workflow (slack)

---

apps/storybook/.storybook/theme.js

Endrer brandUrl til å passe nytt domene.
/Kvib finnes ikke lenger - nå er det "/". 
design.kartverket.no

komp-337-logo

---

.changeset/empty-readers-serve.md
apps/storybook/stories/components/search/search-async/SearchAsync.mdx
apps/storybook/stories/components/search/search-async/SearchAsync.stories.tsx
packages/react/src/search-async/SearchAsync.tsx

Endrer dokumentasjon for searchAsync i henhold til mal. 
Legger også til et par ekstra props i searchAsync som kan være nyttig.

Komp-355-searchAsync

---

.changeset/modern-zoos-share.md
apps/storybook/stories/components/search/search/Search.mdx
apps/storybook/stories/components/search/search/Search.stories.tsx
packages/react/src/icon/Icon.tsx
packages/react/src/search/Search.tsx

Ender utformingen på search for å legge til muligheten for å legge til tekst på søkeknappen. 
Endringer:
- Legger til width i span på Icon for å sørge for at det ikke blir layout shift under lasting av Icon. 
- Fjerner left og right icon prop på Search (Breaking change - major changeset)
- Legger til muligheten å legge til tekst på Search ved å bruke enten iconButton eller searchButton. Det var ikke mulig å bruke en av de på grunn av at de er utformet litt forskjellig.
Kan se litt rart ut i storybook når man bytter props fordi det er en padding som blir regnet ut på render.

Komp-364-searchButtonText

---

apps/storybook/.storybook/MDXContainer.jsx
apps/storybook/.storybook/docs-root.css
apps/storybook/.storybook/preview.js
apps/storybook/stories/design/ColorPalettes.tsx
apps/storybook/stories/design/design-tokens/Colors.tsx
apps/storybook/stories/design/design-tokens/design-tokens.mdx
apps/storybook/stories/documentation/introduksjon.mdx
apps/storybook/stories/templates/DocsHeading.tsx
apps/storybook/stories/templates/DocsStory.tsx

Legger til innholdsfortegnelse! 
Storybook sin versjon av toc er litt buggy - jeg får ikke fjernet den på docs hvor det ikke helt lønner seg å ha den. For eksempel så vil headings fra stories (kode) også bli med i innholdsfortegnelse🤦‍♂️ 
Jeg har fikset den sånn at innholdsfortegnelsen forsvinner dersom det er mindre enn 2 headings på siden. 
Alt i alt vurderer jeg det som at det er bedre å ha den enn å ikke ha den på grunn av bugs. Den funker veldig smooth utenom det!
h2 og h3 vil bli med i innholdsfortegnelsen!

Komp-386-toc

---

apps/storybook/stories/components/spinner/Spinner.mdx

fikset en liten feilkopiering ellernoe

Fikset dobbel retningslinjer banner

---

.changeset/nice-guests-mix.md
apps/storybook/stories/design/Icon.stories.tsx
packages/react/src/icon/Icon.tsx

Legger til muligheten for å kunne endre på ikonstørrelse til hva som helst. Dette er slik at man kan lage mindre knapper med ikoner osv. 
Etter dette burde [komp-397](https://kartverket.atlassian.net/jira/software/projects/KOMP/boards/80?selectedIssue=KOMP-397) utvikles.

komp-394-ikonstørrelse

---

apps/storybook/stories/documentation/komponenter/Components.tsx

Jeg så etter merge av komponentoversikt så fungerte ikke innholdsfortegnelse på den siden. 
Her kommer en kjapp fix - man må legge inn id på headings for at overskriften skal telles i innholdsfortegnelsen.

Fix innholdsfortegnelse

---

.changeset/chilled-stingrays-drive.md
apps/storybook/stories/components/sideelementer/footer/footer-inline/FooterInline.stories.tsx
packages/react/src/footer-inline/FooterInline.tsx

Team Smia har en egen personvernerklæring for nibas, som spesifikt forklarer hvorfor personnummer blir lagret i løsningen. Ønsket derfor en måte å override standardlenken til personvernerklæringen i komponenten `footer-inline`.
Det er ingen designendringer i denne PRen.

prop for personvernerklæring

---

apps/storybook/stories/components/skjemaelementer/timepicker/Timepicker.stories.tsx

Jeg har lagt til to nye stories, som viser hvordan fargen settes for alle komponentene på en nettside via provideren som wrapper hele appen. Når koden virker akkurat som den skal så skal fargen til timepickeren bli riktig for begge storyene, ut i fra hvilket tema som er valgt i provideren.

Lagt til storyes for å teste farge med ulik provider

---

apps/storybook/.storybook/test-runner.ts
apps/storybook/stories/components/skjemaelementer/timepicker/Timepicker.stories.tsx

Added tags to test-runner config file, excluded Timepicker green and blue providers from accessibility tests.

Komp-439-test-runner

---

apps/storybook/stories/components/navigasjon/tabs/tab.stories.tsx

isSelected er ikke en property i `<Tab>` komponenten, men det er dokumentasjon i storybook som viser det, isSelected gjør altså ingenting.

Fjern isSelected fra tab

---

.github/workflows/slack-notify.yml
README.md
apps/storybook/stories/components/sideelementer/header/Header.mdx
apps/storybook/stories/components/sideelementer/header/Header.stories.tsx
apps/storybook/stories/documentation/bidra/Bygge.mdx
apps/storybook/stories/documentation/bidra/KjenteProblemer.mdx
apps/storybook/stories/documentation/bidra/Style.mdx
apps/storybook/stories/documentation/taIBruk.mdx

Fjernet ordet KVIB fra alle steder jeg fant det i tekst og beskrivelser, og byttet ut med Kartverkets designsystem eller designsystemet. Jeg har også oppdatert URL-en, der hvor det var brukt gammel url for dokumentasjonssiden.
Ordet KVIB er fremdeles veldig mye brukt i kode, det er ikke endret i denne pull-requesten.

Endre fra KVIB til Kartverkets designsystem en rekke steder.

---

.changeset/tame-zebras-happen.md
apps/storybook/stories/components/media/icon/Icon.stories.tsx
packages/react/src/icon/Icon.tsx

La til et valg for å sette `aria-hidden` til `true` for ikoner for å gjøre det mulig å hindre at skjermlesere leser opp ikonnavnet fra Material Symbols.

Komp-454: Støtte for å skjule aria på ikoner

---

.changeset/tall-bikes-change.md
apps/storybook/stories/components/knapper/button/Button.stories.tsx
packages/react/src/button/Button.tsx

Bruker utvider `Button` til å kunne ta inn en prop for om `ariaIsHidden` skal bli satt på tilhørende ikon for vanlige knapper med `rightIcon` og `leftIcon`. Dette bør nok ikke være et valg på vanlig `IconButton` siden aria-label bør settes uansett når disse komponentene ikke inneholder annen tekst uansett, så har derfor valgt å kun utvide den vanlige `Button`.
Denne kan brukes for å unngå at en `<Button leftIcon="login">Logg inn</Button>` leses opp som "login Logg inn" av en skjermleser.

Komp-454-2: Støtte for å skjule aria på ikoner tilhørende knapper

---

.changeset/tasty-geese-buy.md
apps/storybook/stories/documentation/bidra/Bygge.mdx
packages/react/src/datepicker/Datepicker.tsx
packages/react/src/theme/components/datepicker.ts
packages/react/src/theme/components/index.ts

Dersom man setter default fargetema som instruert i [dokumentasjonen](https://design.kartverket.no/?path=/docs/info-oppsett--docs#endre-default-farge) vil ikke Datepicker bli satt til riktig farge. Det kommer av at dere setter default colorScheme på komponentnivå og lytter ikke på verdien som er satt i theme. Da må konsumentene sette colorScheme til f.eks. `blue` hvert eneste sted komponent brukes, og det kan fikses.
Dette skal ikke føre til noen merkbar endring for de fleste brukerne.
Fjernet også eksempel av feilaktig bruk fra Bygge.mdx

Setter default datepicker colorscheme på theme-nivå

---

.changeset/eighty-fireants-buy.md
apps/storybook/.storybook/preview.js
apps/storybook/stories/components/skjemaelementer/datepicker/Datepicker.mdx
apps/storybook/stories/components/skjemaelementer/timepicker/Timepicker.stories.tsx
apps/storybook/stories/documentation/taIBruk.mdx
packages/react/src/datepicker/Datepicker.tsx
packages/react/src/header/Header.tsx
packages/react/src/provider/KvibProvider.tsx
packages/react/src/theme/index.ts
packages/react/src/timepicker/Timepicker.tsx

Gikk litt fort i svingene sist (#779), testingen fungerte innad i kvib, men ikke som en ekstern pakke. Problemet kommer av at når man bruker `theme`-konstanten i kvib så henter man i praksis ned _default_ theme, ikke theme-verdien som mates inn i KvibProvider. Med andre ord ville ikke eksterne temaer fungere fordi kvib bare brukte sitt eget default theme uansett hva. Løsningen er å bruker `useTheme`-hooken som henter theme fra KvibContext i stedet, enkelt og greit.
Dette er et problem som egentlig ligger ganske mange steder i kodebasen, men er i hovedsak knyttet til bruk av farger. Siden konsumenter av designsystemer antageligvis bruker de samme fargepalettene så kommer ikke det til å bli et problem med det første, men det er noe noen™️ bør se på å bytte ut. Det gjelder også tilfeller der …

Omdøp theme og fiks bruk av theme til datepickers

---

.changeset/ninety-lobsters-grab.md
apps/storybook/stories/components/search/search-async/SearchAsync.stories.tsx
packages/react/src/search-async/SearchAsync.tsx

Legger til muligheten for å formattere options som vises i dropdownen til AsyncSearch-komponenten. Denne proppen ligger allerede på den underliggende chakra komponenten så mesteparten av jobben var bare å tilgjengeliggjøre denne. Lagde et nytt eksempel i storybook som viser hvordan man kan bruke den. 

Add optionLabelFormatter for SearchAsync

---

apps/storybook/stories/introduksjon.mdx
package-lock.json

Endret på href slik at knappene på oversiktsiden virket igjen. 
Design tokens ble delt opp til flere sider, så jeg valgte å peke mot fargetokens som en midlertidig løsning.

BUG: Snarveier på velkomstsiden leder til feil adresse

---

.changeset/cold-guests-thank.md
apps/storybook/stories/components/search/search-async/SearchAsync.mdx
apps/storybook/stories/components/search/search-async/SearchAsync.stories.tsx
package-lock.json
packages/react/src/search-async/SearchAsync.tsx
packages/react/src/search-async/index.tsx

Vi hadde behov for å sette focus på SearchAsync input feltet, så trenger refen. Legger til dette som prop til SearchAsync.

KOMP-467 Mulighet for bruk av ref på SearchAsync

---

.changeset/dull-kiwis-float.md
packages/react/src/theme/components/alert.ts

Loading status på toast/alert har nå riktig blåfarge
Før:
Etter:

Kvd 470 farge loading toast

---

.changeset/khaki-cooks-sit.md
apps/storybook/stories/components/sideelementer/header/Header.stories.tsx
packages/react/src/header/Header.tsx

Adding another prop to the `Header` component to be able to change behaviour of the link.
Found that the `isExternal={false}` was not enough for our use case.
We have a create-react-app project with tanstack-query and with our setup the link is still behaving as an external link, reseting the browser state which prevents us from keeping our caching. 
I have not tried multiple setups so I can't tell how it is for other systems like remix or next.
By using the `as` property we can remain within our context. By doing this we have the ability to use that property.

Added linkProps as a prop to be able to change the functionality for the link within the header.

---

apps/storybook/.storybook/docs-root.css
apps/storybook/stories/documentation/utils/Components.tsx
apps/storybook/stories/documentation/utils/IntroButton.tsx

Endret på styling slik at man ikke må legge til en egen klasse på ikoner når man jobber i storybook.

Ikoner i Storybook-dokumentasjon

---

package-lock.json
package.json
turbo.json

Fjerner ubrukte avhengigheter (`esbuild`, `eslint-config-custom`) og oppdaterer utdaterte pakker som dependabot ikke helt fikk til.
<!-- Sjekk av disse punktene for hver endring. Disse utgjør et minimum av sjekker som skal være gjennomført før PR-en merges. For mer informasjon om hvordan du kan bidra med kode til designbiblioteket, se https://design.kartverket.no/?path=/docs/for-utviklere-bidra-med-kode-hurtigveiledning--docs>

Rydder opp i avhengigheter

---

apps/storybook/stories/documentation/utils/IntroCard.tsx
apps/storybook/stories/introduksjon.mdx

Inntil videre blir lenken til komponentoversikten fjernet ettersom at denne ikke virker akkurat nå. Informasjon om spørreskjema fjernes også til fordel for nytt skjema som legges ut på Slack.
<!-- Sjekk av disse punktene for hver endring. Disse utgjør et minimum av sjekker som skal være gjennomført før PR-en merges. For mer informasjon om hvordan du kan bidra med kode til designbiblioteket, se https://design.kartverket.no/?path=/docs/for-utviklere-bidra-med-kode-hurtigveiledning--docs>

Fjerner kort fra landingsside

---

.changeset/pretty-melons-beam.md
packages/react/src/theme/components/slider.ts
packages/react/src/theme/components/switch.ts

Track-fargen på `Slider` og `Switch` er litt i det mørkeste laget. Etter innspill fra @erlendst jekkes disse grå bakgrunnsfargene fra `gray.400` til den litt lysere `gray.300`-fargen.
Før:
Etter:

Justerer track-farger fra 400 til 300 på Switch og Slider

---

apps/storybook/stories/components/skjemaelementer/datepicker/Datepicker.stories.tsx
packages/react/src/datepicker/Datepicker.tsx

Placeholder sendes gjennom propsene til Datepickeren, så det er unødvendig med en statisk placeholder i komponenten som krangler med den som sendes inn.

Fjerner statisk placeholder i Datepicker

---

.changeset/wise-spiders-rest.md
packages/react/src/search/Search.tsx

Etter gode innspill fra @perzonas og @joonerik droppes `RenderInputGroup` som wrappet rundt inputtgruppen i en arrow function siden dette tegnet opp komponenten på nytt og på nytt.

Retter feil som førte til tap av fokus i Search

---

.github/workflows/preview.yml
apps/storybook/package.json
apps/storybook/stories/components/overlay/alert-dialog/AlertDialog.mdx
apps/storybook/stories/components/overlay/alert-dialog/AlertDialog.stories.tsx
apps/storybook/stories/components/overlay/alert-dialog/srcStrings.ts
apps/storybook/stories/components/overlay/modal/Modal.mdx
apps/storybook/stories/components/overlay/modal/Modal.stories.tsx
apps/storybook/stories/components/overlay/modal/srcStrings.ts
apps/storybook/stories/documentation/komponentoversikt/Komponenter.tsx
apps/storybook/stories/templates/DocsContainer.tsx

Endrer Modal og AlertDialog sine stories til å bruke Canvas med kodeeksempler som er skjult som standard. Innholdet i modalene som popper opp i eksemplene har også blitt mer overordnede, samt at de benytter seg av best practices når det kommer til knappeposisjoner og variant-hierarki.
Før/etter på standard modal:

Oppdaterer dokumentasjon for Modal og AlertDialog

---

.changeset/two-weeks-try.md
apps/storybook/stories/components/sideelementer/footer/footer/Footer.mdx
apps/storybook/stories/components/sideelementer/footer/footer/Footer.stories.tsx
packages/react/src/footer/Footer.tsx

Etter innspill fra teamene som bruker `Footer` er det behov for å fjerne alle elementer fra denne komponenten, og frem til nå har man kunne fjerne alt utenom lenken til Kartverkets personvernsider. Denne PR-en legger til prop-en `excludePrivacyLink` som brukes på samme måte som de eksisterende `exclude`-lenkene for å kunne ta bort nettopp denne personvernslenken.
Fra nå vil det være mulig å strippe Footeren ned til å kun inneholde logo:

Støtte for å fjerne personvernslenke i Footer

---

.changeset/many-walls-sit.md
apps/storybook/.storybook/docs-root.css
apps/storybook/stories/components/skjemaelementer/datepicker/Datepicker.stories.tsx
packages/react/src/datepicker/Datepicker.tsx

En bug i parsingen av datoer i `Daypicker` gjorde at ugyldige datoer hindret `onChange` å bli kjørt, og en oppdatering i `date-fns` gjorde at denne sjekken måtte gjøres litt annerledes enn før og dermed klagde på ugyldige datoer. Retter opp i dette nå 🤞🏼

Fikser bug i Datepicker

---

.changeset/cool-socks-compete.md
apps/storybook/.storybook/preview.tsx
apps/storybook/stories/components/skjemaelementer/datepicker/Datepicker.stories.tsx
packages/react/src/datepicker/Datepicker.tsx

Gir et lite løft til Datepicker for å støtte det å skrive inn datoer i tekstfeltet igjen. Her støttes det nå flere skrivemåter hvor 29.10.24 blir tolket som 29.10.2024, og det samme gjelder for 29/10/24 og 29/10/2024. `onChange` som sendes inn til komponenten trigges både ved bruk av inputfelt og gjennom valg av dato i kalenderen, i tillegg til på `onBlur` når man fjerner fokus fra tekstfeltet.

Refaktorerer Datepicker

---

.changeset/metal-coins-fly.md
apps/storybook/stories/components/search/search-async/SearchAsync.stories.tsx
packages/react/src/search-async/SearchAsync.tsx

Legger til menuPlacement som en prop for SearchAsync så man kan velge om menyen skal være over, under eller auto (den siden som har plass). 
<!-- Sjekk av disse punktene for hver endring. Disse utgjør et minimum av sjekker som skal være gjennomført før PR-en merges. For mer informasjon om hvordan du kan bidra med kode til designbiblioteket, se https://design.kartverket.no/?path=/docs/for-utviklere-bidra-med-kode-hurtigveiledning--docs>

Legger til menuPlacement prop for SearchAsync

---

.changeset/unlucky-laws-whisper.md
apps/storybook/stories/components/accordion/Accordion.stories.tsx
packages/react/src/accordion/index.ts
packages/react/src/alert/index.ts
packages/react/src/checkbox-card/index.ts
packages/react/src/components/ui/accordion.tsx
packages/react/src/components/ui/alert.tsx
packages/react/src/components/ui/checkbox-card.tsx
packages/react/src/components/ui/dialog.tsx
packages/react/src/components/ui/field.tsx
packages/react/src/components/ui/popover.tsx
packages/react/src/components/ui/radio-card.tsx
packages/react/src/components/ui/separator.tsx
packages/react/src/components/ui/table.tsx
packages/react/src/dialog/index.ts
packages/react/src/field/index.ts
packages/react/src/popover/index.ts
packages/react/src/radio-card/index.ts
packages/react/src/separator/index.ts
packages/react/src/table/index.ts

En rekke komponenter skulle vært markert som `@deprecated` fra før, men dette virket ikke siden det var selve aliasene som ble markert istedenfor at man oppretter et nytt objekt og setter dette som deprecated (ref. [denne tråden](https://github.com/palantir/tslint/issues/3751#issuecomment-370265475). Nå er dette fikset

Markerer flere komponenter som deprecated

---

packages/react/package.json

Ser ikke ut som KVIB benytter seg av react 19, så overlater peer dependency resolution til å tillate versjoner fra og med React 18

chore: Downgrade react dependency to >= 18

---

.changeset/dark-moments-stop.md

Trigger en versjonsoppdatering av forrige PR som åpnet opp React peerDependency til å tillate versjon 18 og oppover.
https://github.com/kartverket/kvib/pull/1002

Allow React 18 and up as peer dependency

---

.changeset/purple-paws-vanish.md
packages/react/src/header/Header.tsx

- Aligner content i dropdown til venstre istedenfor midten
- Viser alltid content slik at det kan velges fra brukeren av komponenten
- Grupperer menyknapp og content slik at det kun blir to deler i headeren
- [ x Dersom det er lagt til ny funksjonalitet er det også lagt til stories og dokumentasjon på denne i storybook. Stories skal dekke de viktigste tilstandene visuelt, og blir blant annet brukt til å kjøre automatisk testing av universell utforming, i tillegg til dokumentasjon.

Små forbedringer på Header

---

.changeset/many-otters-float.md
apps/storybook/.storybook/main.ts
package-lock.json
packages/react/src/header/Header.tsx

Midtstiller tittel dersom logovarianten er noe annet enn horizontal
Endrer styling slik at tittel blir midstilt dersom logovariant er symbol. Med horizontal blir den som før.
_Gjorde en liten endring i main for å få prosjektet til å bygge med node 22+_
Før:
Etter:

Fikser styling på mobil i Header
